
static inline const char *help_strings_en[] = {
	"Close me ..",
	"Connect Device",
	"Stop session with device",
	"ADB Device Management",
	"Show in original size",
	"Show cursor position",
	"Save frame to file",
	"Save frame to selected file",
	"Full screen (experimental)",
	"Install APK package",
	"",
	"Image saved to file",
	"Device connected",
	"Device Disabled",
	"The device is already connected",
	"The device is already disabled",
	"Error installing utilities on the device, check the connection, the ADB manager may not be running.",
	"ADB Android Viewer",
	"AndroidViewer",
	"ADBVCapture-",
	"plugin-lua",
	"Android Viewer Error:",
	"ADB Error Driver:",
	"Unknown error, please provide details: https://clnviewer.github.io/ADB-Android-Viewer/",
	"Enter text:",
	nullptr
};
