
static inline const char *help_strings_dm[] = {
    "Schließ mich ..",
    "Gerät verbinden",
    "Sitzung mit Gerät beenden",
    "ADB Device Management",
    "In Originalgröße anzeigen",
    "Cursorposition anzeigen",
    "Frame in Zwischenablage kopieren",
    "Rahmen in Datei speichern",
    "Rahmen in ausgewählter Datei speichern",
    "Vollbild (experimentell)",
    "Installiere APK Package",
    "",
    "Bild in Datei gespeichert",
    "Bild in die Zwischenablage kopiert",
    "Gerät angeschlossen",
    "Gerät deaktiviert",
    "Das Gerät ist bereits verbunden",
    "Das Gerät ist bereits deaktiviert",
    "Fehler beim Installieren der Dienstprogramme auf dem Gerät. Überprüfen Sie die Verbindung. Der ADB-Manager wird möglicherweise nicht ausgeführt.",
    "ADB Android Viewer",
    "AndroidViewer",
    "ADBVCapture-",
    "plugin-lua",
    "Android Viewer-Fehler:",
    "ADB-Fehlertreiber:",
    "Unbekannter Fehler, bitte Details angeben: https://clnviewer.github.io/ADB-Android-Viewer/",
    "Text eingeben:",
    "Bender: Ich werde bald kommen ..",
    "Bender: Ich schalte aus ..",
    "! ADB unterstützt keinen Eingabetext in der Landessprache !",
    "! ADB not support input text in national language !",
    nullptr
};
