
static inline const char *help_strings_cn[] = {
    "关我......",
    "连接设备",
    "停止与设备会话",
    "亚行设备管理",
    "以原始尺寸显示",
    "显示光标位置",
    "将框架复制到剪贴板",
    "将帧保存到文件",
    "将帧保存到选定文件",
    "全屏（实验）",
    "安装APK套餐",
    "",
    "图片保存到文件",
    "图像复制到剪贴板",
    "设备已连接",
    "设备已禁用",
    "设备已经连接",
    "该设备已被禁用",
    "在设备上安装实用程序时出错，检查连接，ADB管理器可能没有运行。",
    "ADB Android Viewer",
    "AndroidViewer"
    "ADBVCapture-"
    "插件 - 卢阿"
    "Android Viewer错误：",
    "ADB错误驱动程序：",
    "未知错误，请提供详细信息：https：//clnviewer.github.io/ADB-Android-Viewer/",
    "输入文字：",
    "本德：我很快就会来......",
    "本德：我关掉......",
    "！ 亚行不支持国家语言的输入文字 ！",
    "! ADB not support input text in national language !",
    "“关闭并保存脚本",
    "关闭终端",
    "终端窗口太小，无法显示命令",
    "浏览器窗口太小，无法显示命令。",
    "文件概述",
    "设备信息",
    "APK包装信息",
    "显示支持APK的软件包",
    "显示APK已禁用的包",
    "显示APK系统包",
    "显示APK第三方套餐",
    "显示本地文件",
    "在远程设备上显示文件",
    "从菜单中选择要显示的项目",
    "Error move file: ",
    "File moved to: ",
    "Error send file: ",
    "File copied to: ",
    "File deleted: ",
    "Error delete, file: ",
    "Change permission status: ",
    "Permission changed to ",
    "Error change permission, file: ",
    "UnInstall ",
    "UnInstall error: ",
    nullptr
};
