
static inline const char *help_strings_en[] = {
	"Close me ..",
	"Connect Device",
	"Stop session with device",
	"ADB Device Management",
	"Show in original size",
	"Show cursor position",
	"Copy frame to clipboard",
	"Save frame to file",
	"Save frame to selected file",
	"Full screen (experimental)",
	"Install APK package",
	"",
	"Image saved to file",
	"Image copied to clipboard",
	"Device connected",
	"Device Disabled",
	"The device is already connected",
	"The device is already disabled",
	"Error installing utilities on the device, check the connection, the ADB manager may not be running.",
	"ADB Android Viewer",
	"AndroidViewer",
	"ADBVCapture-",
	"plugin-lua",
	"Android Viewer Error:",
	"ADB Error Driver:",
	"Unknown error, please provide details: https://clnviewer.github.io/ADB-Android-Viewer/",
	"Enter text:",
	"Bender: I will come soon ..",
	"Bender: I turn off ..",
	"! ADB not support input text in national language !",
	"! ADB not support input text in national language !",
	"Close and Save Script",
	"Close terminal",
	"Terminal window too small to display command",
	"The browser window is too small to display a command",
	"Browse Files",
	"Device info",
	"Information about APK packages",
	"Show APK enabled packages",
	"Show APK disabled packages",
	"Show APK system packages",
	"Show APK third party packages",
	"Show local files",
	"Show files on remote device",
	"Select an item from\nthe menu to display",
	"Error move file: ",
	"File moved to: ",
	"Error send file: ",
	"File copied to: ",
	"File deleted: ",
	"Error delete, file: ",
	"Change permission status: ",
	"Permission changed to ",
	"Error change permission, file: ",
	"APK uninstalled:  ",
	"APK uninstall error: ",
	nullptr
};
