
static inline const char *help_strings_dm[] = {
    "Schließ mich ..",
    "Gerät verbinden",
    "Sitzung mit Gerät beenden",
    "ADB Device Management",
    "In Originalgröße anzeigen",
    "Cursorposition anzeigen",
    "Frame in Zwischenablage kopieren",
    "Rahmen in Datei speichern",
    "Rahmen in ausgewählter Datei speichern",
    "Vollbild (experimentell)",
    "Installiere APK Package",
    "",
    "Bild in Datei gespeichert",
    "Bild in die Zwischenablage kopiert",
    "Gerät angeschlossen",
    "Gerät deaktiviert",
    "Das Gerät ist bereits verbunden",
    "Das Gerät ist bereits deaktiviert",
    "Fehler beim Installieren der Dienstprogramme auf dem Gerät. Überprüfen Sie die Verbindung. Der ADB-Manager wird möglicherweise nicht ausgeführt.",
    "ADB Android Viewer",
    "AndroidViewer",
    "ADBVCapture-",
    "plugin-lua",
    "Android Viewer-Fehler:",
    "ADB-Fehlertreiber:",
    "Unbekannter Fehler, bitte Details angeben: https://clnviewer.github.io/ADB-Android-Viewer/",
    "Text eingeben:",
    "Bender: Ich werde bald kommen ..",
    "Bender: Ich schalte aus ..",
    "! ADB unterstützt keinen Eingabetext in der Landessprache !",
    "! ADB not support input text in national language !",
    "Skript schließen und speichern",
    "Skript konnte nicht im editor geöffnet werden, datei fehlt?",
    "Terminal schließen",
    "Terminalfenster zu klein zum anzeigen des befehls",
    "Das Browserfenster ist zu klein, um einen Befehl anzuzeigen.",
    "Dateien durchsuchen",
    "Geräteinformationen",
    "Informationen zu APK-Paketen",
    "APK-fähige Pakete anzeigen",
    "APK deaktivierte Pakete anzeigen",
    "APK-Systempakete anzeigen",
    "APK-Pakete von Drittanbietern anzeigen",
    "Lokale Dateien anzeigen",
    "Dateien auf dem Remote-Gerät anzeigen",
    "Wählen Sie aus dem Menü\neinen Eintrag aus,\nder angezeigt werden soll",
    "Fehler beim Verschieben der Datei: ",
    "Datei verschoben nach: ",
    "Fehler beim Senden der Datei: ",
    "Datei kopiert nach: ",
    "Datei gelöscht: ",
    "Fehler beim Löschen, Datei: ",
    "Berechtigungsstatus ändern: ",
    "Berechtigung geändert zu ",
    "Fehler Änderungsberechtigung, Datei: ",
    "Deinstallation ",
    "Deinstallationsfehler: ",
    nullptr
};
