
static inline const char *popup_strings_en[] = {
    /* 0 */ "Screenshot",
    /* 1 */ "Install APK",
    /* 2 */ "Disconnect Device",
    /* 3 */ "Exit",
    /* 4 */ "Save",
    /* 5 */ "Save As ..",
    /* 6 */ "Lua script",
    /* 7 */ "Write script",
    /* 8 */ "Save Script",
    /* 9 */ "Set a script destination",
    /* 10 */ "Continue editing script",
    /* 11 */ "Cancel ..",
    /* 12 */ "Plugins",
    /* 13 */ "Type of script",
    /* 14 */ "Check & Click",
    /* 15 */ "Click",
    /* 16 */ "Device Commands",
    /* 17 */ "- home (3)",
    /* 18 */ "- close (111)",
    /* 19 */ "- program history (187)",
    /* 20 */ "- settings (176)",
    /* 21 */ "- contacts (207)",
    /* 22 */ "- calendar (208)",
    /* 23 */ "- music (209)",
    /* 24 */ "- Google assist (219)",
    /* 25 */ "- device: sleep (223)",
    /* 26 */ "- device: activation (224)",
    /* 27 */ L"Language",
    /* 28 */ L"Russian",
    /* 29 */ L"English",
    /* 30 */ L"German",
    /* 31 */ L"Chinese",
    nullptr
};
