
static inline const wchar_t *popup_strings_en[] = {
    /* 0 */ L"Screenshot",
    /* 1 */ L"Install APK",
    /* 2 */ L"Disconnect Device",
    /* 3 */ L"Exit",
    /* 4 */ L"Save",
    /* 5 */ L"Save As ..",
    /* 6 */ L"Lua script",
    /* 7 */ L"Write script",
    /* 8 */ L"Save Script",
    /* 9 */ L"Set a script destination",
    /* 10 */ L"Continue editing script",
    /* 11 */ L"Cancel ..",
    /* 12 */ L"Plugins",
    /* 13 */ L"Type of script",
    /* 14 */ L"Check & Click",
    /* 15 */ L"Click",
    /* 16 */ L"Device Commands",
    /* 17 */ L"- home (3)",
    /* 18 */ L"- close (111)",
    /* 19 */ L"- program history (187)",
    /* 20 */ L"- settings (176)",
    /* 21 */ L"- contacts (207)",
    /* 22 */ L"- calendar (208)",
    /* 23 */ L"- music (209)",
    /* 24 */ L"- Google assist (219)",
    /* 25 */ L"- device: sleep (223)",
    /* 26 */ L"- device: activation (224)",
    /* 27 */ L"Language",
    /* 28 */ L"Russian",
    /* 29 */ L"English",
    /* 30 */ L"German",
    /* 31 */ L"Chinese",
    /* 32 */ L"Display",
    /* 33 */ L"Ratio",
    /* 34 */ L"Rotate",
    /* 35 */ L"Bender Rodriguez",
    /* 36 */ L"Landscape",
    /* 37 */ L"Portrait",
    /* 38 */ L"1:1",
    /* 39 */ L"1:2",
    /* 40 */ L"1:3",
    /* 41 */ L"Save configuration",
    /* 42 */ L"Copy",
    /* 43 */ L"Mirror Image",
    /* 44 */ L"Text entry field",
    /* 45 */ L"Terminal",
    /* 46 */ L"Notify open/expand",
    /* 47 */ L"Notify close/collapse",
    nullptr
};
