
static inline const char *popup_strings_dm[] = {
    /* 0 */ "Screenshot",
    /* 1 */ "Installiere APK",
    /* 2 */ "Gerät trennen",
    /* 3 */ "Beenden",
    /* 4 */ "Speichern",
    /* 5 */ "Speichern unter ..",
    /* 6 */ "Lua script",
    /* 7 */ "Schreibe Skript",
    /* 8 */ "Skript speichern",
    /* 9 */ "Festlegen eines Skriptziels",
    /* 10 */ "Skript weiter bearbeiten",
    /* 11 */ "Abbrechen ..",
    /* 12 */ "Plugins",
    /* 13 */ "Art des Skripts",
    /* 14 */ "Check & Click",
    /* 15 */ "Klick",
    /* 16 */ "Gerätebefehle",
    /* 17 */ "- home (3)",
    /* 18 */ "- close (111)",
    /* 19 */ "- Programmverlauf (187)",
    /* 20 */ "- Einstellungen (176)",
    /* 21 */ "- Kontakte (207)",
    /* 22 */ "- Kalender (208)",
    /* 23 */ "- Musik (209)",
    /* 24 */ "- Google assist (219)",
    /* 25 */ "- Gerät: Sleep (223)",
    /* 26 */ "- Gerät: Aktivierung (224)",
    /* 27 */ "Sprache",
    /* 28 */ "Russisch",
    /* 29 */ "Englisch",
    /* 30 */ "Deutsch",
    /* 31 */ "Chinesisch",
    /* 32 */ "Anzeige",
    /* 33 */ "Proportionen",
    /* 34 */ "Orientierung",
    /* 35 */ "Bender Rodriguez",
    /* 36 */ "Landschaft",
    /* 37 */ "Portrait",
    /* 38 */ "1:1",
    /* 39 */ "1:2",
    /* 40 */ "1:3",
    /* 41 */ "Konfiguration speichern",
    nullptr
};
