
static inline const wchar_t *popup_strings_dm[] = {
    /* 0 */ L"Screenshot",
    /* 1 */ L"Installiere APK",
    /* 2 */ L"Ger„t trennen",
    /* 3 */ L"Beenden",
    /* 4 */ L"Speichern",
    /* 5 */ L"Speichern unter ..",
    /* 6 */ L"Lua script",
    /* 7 */ L"Schreibe Skript",
    /* 8 */ L"Skript speichern",
    /* 9 */ L"Festlegen eines Skriptziels",
    /* 10 */ L"Skript weiter bearbeiten",
    /* 11 */ L"Abbrechen ..",
    /* 12 */ L"Plugins",
    /* 13 */ L"Art des Skripts",
    /* 14 */ L"Check & Click",
    /* 15 */ L"Klick",
    /* 16 */ L"Ger„tebefehle",
    /* 17 */ L"- home (3)",
    /* 18 */ L"- close (111)",
    /* 19 */ L"- Programmverlauf (187)",
    /* 20 */ L"- Einstellungen (176)",
    /* 21 */ L"- Kontakte (207)",
    /* 22 */ L"- Kalender (208)",
    /* 23 */ L"- Musik (209)",
    /* 24 */ L"- Google assist (219)",
    /* 25 */ L"- Ger„t: Sleep (223)",
    /* 26 */ L"- Ger„t: Aktivierung (224)",
    /* 27 */ L"Sprache",
    /* 28 */ L"Russisch",
    /* 29 */ L"Englisch",
    /* 30 */ L"Deutsch",
    /* 31 */ L"Chinesisch",
    /* 32 */ L"Anzeige",
    /* 33 */ L"Proportionen",
    /* 34 */ L"Orientierung",
    /* 35 */ L"Bender Rodriguez",
    /* 36 */ L"Landschaft",
    /* 37 */ L"Portrait",
    /* 38 */ L"1:1",
    /* 39 */ L"1:2",
    /* 40 */ L"1:3",
    /* 41 */ L"Konfiguration speichern",
    /* 42 */ L"Kopieren",
    /* 43 */ L"Mirror Image",
    nullptr
};
