
static inline const char *popup_strings_en[] = {
    /* 0 */ "Screenshot",
    /* 1 */ "Install APK",
    /* 2 */ "Disconnect Device",
    /* 3 */ "Exit",
    /* 4 */ "Save",
    /* 5 */ "Save As ..",
    /* 6 */ "Lua script",
    /* 7 */ "Write script",
    /* 8 */ "Save Script",
    /* 9 */ "Set a script destination",
    /* 10 */ "Continue editing script",
    /* 11 */ "Cancel ..",
    /* 12 */ "Plugins",
    /* 13 */ "Type of script",
    /* 14 */ "Check & Click",
    /* 15 */ "Click",
    /* 16 */ "Device Commands",
    /* 17 */ "- home (3)",
    /* 18 */ "- close (111)",
    /* 19 */ "- program history (187)",
    /* 20 */ "- settings (176)",
    /* 21 */ "- contacts (207)",
    /* 22 */ "- calendar (208)",
    /* 23 */ "- music (209)",
    /* 24 */ "- Google assist (219)",
    /* 25 */ "- device: sleep (223)",
    /* 26 */ "- device: activation (224)",
    /* 27 */ "Language",
    /* 28 */ "Russian",
    /* 29 */ "English",
    /* 30 */ "German",
    /* 31 */ "Chinese",
    /* 32 */ "Display",
    /* 33 */ "Ratio",
    /* 34 */ "Rotate",
    /* 35 */ "Bender Rodriguez",
    /* 36 */ "Landscape",
    /* 37 */ "Portrait",
    /* 38 */ "1:1",
    /* 39 */ "1:2",
    /* 40 */ "1:3",
    /* 41 */ "Save configuration",
    /* 42 */ "Copy",
    /* 43 */ "Mirror Image",
    /* 44 */ "Text entry field",
    /* 45 */ "Terminal",
    /* 46 */ "Notify open/expand",
    /* 47 */ "Notify close/collapse",
    /* 48 */ "Terminal - indent from bottom edge",
    /* 49 */ "Device info",
    /* 50 */ "Version Information",
    /* 51 */ "Device",
    /* 52 */ "Driver Information",
    nullptr
};
