.TH "GameDev::ADBDriver::Swipe_s" 3 "Mon Sep 9 2019" "ADBDriverDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameDev::ADBDriver::Swipe_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBx0\fP"
.br
.ti -1c
.RI "int32_t \fBy0\fP"
.br
.ti -1c
.RI "int32_t \fBx1\fP"
.br
.ti -1c
.RI "int32_t \fBy1\fP"
.br
.ti -1c
.RI "int32_t \fBt\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ADBDriverDLL from the source code\&.
