.TH "GameDev::StyleDialog" 3 "Mon Sep 9 2019" "ADBDriverDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameDev::StyleDialog
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "COLORREF \fBRGBColorTxt\fP () const"
.br
.ti -1c
.RI "COLORREF \fBRGBColorTxtDefault\fP () const"
.br
.ti -1c
.RI "COLORREF \fBRGBColorTxtButtonDefault\fP () const"
.br
.ti -1c
.RI "COLORREF \fBRGBColorBg\fP () const"
.br
.ti -1c
.RI "COLORREF \fBRGBColorBgDefault\fP () const"
.br
.ti -1c
.RI "COLORREF \fBRGBColorBgButtonDefault\fP () const"
.br
.ti -1c
.RI "COLORREF \fBRGBColorBgButtonLightDefault\fP () const"
.br
.ti -1c
.RI "HBRUSH \fBBrushBg\fP () const"
.br
.ti -1c
.RI "bool \fBIsDefaultStyle\fP () const"
.br
.ti -1c
.RI "void \fBSet\fP (COLORREF, COLORREF)"
.br
.ti -1c
.RI "INT_PTR \fBColorDialog\fP ()"
.br
.ti -1c
.RI "INT_PTR \fBColorStatic\fP (HDC)"
.br
.ti -1c
.RI "INT_PTR \fBColorStatic\fP (HDC, COLORREF)"
.br
.ti -1c
.RI "\fBStyleDialog\fP (COLORREF, COLORREF)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ADBDriverDLL from the source code\&.
