.TH "GameDev::AdbListDialog" 3 "Mon Sep 9 2019" "ADBDriverDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameDev::AdbListDialog
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "INT_PTR \fBShow\fP (SelectedList &, int32_t, bool)"
.br
.ti -1c
.RI "INT_PTR \fBShow\fP (SelectedList &, int32_t)"
.br
.ti -1c
.RI "INT_PTR \fBShow\fP (SelectedList &)"
.br
.ti -1c
.RI "std::wstring \fBSelectedKey\fP () const"
.br
.ti -1c
.RI "std::wstring \fBSelectedValue\fP () const"
.br
.ti -1c
.RI "\fBAdbListDialog\fP (DWORD)"
.br
.ti -1c
.RI "\fBAdbListDialog\fP (HINSTANCE, DWORD)"
.br
.ti -1c
.RI "\fBAdbListDialog\fP (HINSTANCE, DWORD, COLORREF, COLORREF)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static INT_PTR CALLBACK \fBDialogRedirect\fP (HWND, UINT, WPARAM, LPARAM)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ADBDriverDLL from the source code\&.
