.TH "GameDev::DriverConst" 3 "Mon Sep 9 2019" "ADBDriverDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameDev::DriverConst
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBENUM_PRINTABLE\fP (DeviceInfoType, int32_t, DI_CPU_LIST, DI_VERSION_SDK, DI_VERSION_RELEASE)"
.br
.ti -1c
.RI "\fBENUM_PRINTABLE\fP (KeysType, int32_t, KEYS_ANDROID, KEYS_SDL, KEYS_WINAPI)"
.br
.ti -1c
.RI "\fBENUM_PRINTABLE\fP (CapType, int32_t, CAP_RAW, CAP_PNG, CAP_ACAP_BMP, CAP_ACAP_STREAM)"
.br
.ti -1c
.RI "\fBENUM_PRINTABLE\fP (FilePermissionType, int32_t, PERM_RW=0, PERM_RWX, PERM_RWRW, PERM_RWXRWX, PERM_RWRWRW, PERM_RWXRWXRWX, PERM_NONE)"
.br
.ti -1c
.RI "\fBENUM_PRINTABLE\fP (FileType, int32_t, FILETYPE_NONE=0, FILETYPE_DIR, FILETYPE_FILE, FILETYPE_SYMLINK, FILETYPE_FIFO, FILETYPE_CHARDEV, FILETYPE_BLKDEV, FILETYPE_SOCK, FILETYPE_ROOT, FILETYPE_BACK, FILETYPE_INFO, FILETYPE_READONLY)"
.br
.ti -1c
.RI "\fBENUM_PRINTABLE\fP (ClearType, int32_t, CLEARTYPE_NONE, CLEARTYPE_4, CLEARTYPE_8)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ADBDriverDLL from the source code\&.
