.TH "GameDev::AdbMgrDialog" 3 "Mon Sep 9 2019" "ADBDriverDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameDev::AdbMgrDialog
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFutureData\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "INT_PTR \fBShow\fP ()"
.br
.ti -1c
.RI "INT_PTR \fBShow\fP (\fBADBDriver\fP *)"
.br
.ti -1c
.RI "INT_PTR \fBShow\fP (\fBADBDriver\fP &)"
.br
.ti -1c
.RI "\fBAdbMgrDialog\fP (DWORD)"
.br
.ti -1c
.RI "\fBAdbMgrDialog\fP (HINSTANCE, DWORD)"
.br
.ti -1c
.RI "\fBAdbMgrDialog\fP (HINSTANCE, DWORD, COLORREF, COLORREF)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static INT_PTR CALLBACK \fBDialogRedirect\fP (HWND, UINT, WPARAM, LPARAM)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ADBDriverDLL from the source code\&.
