.TH "GameDev::DriverAsync" 3 "Mon Sep 9 2019" "ADBDriverDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameDev::DriverAsync
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBadd\fP (T, T const &, std::function< bool(T, T const &, T &, DriverConst::ClearType)>)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ADBDriverDLL from the source code\&.
