.TH "LZ4_stream_t_internal" 3 "Mon Sep 9 2019" "ADBDriverDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LZ4_stream_t_internal
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBhashTable\fP [LZ4_HASH_SIZE_U32]"
.br
.ti -1c
.RI "unsigned int \fBcurrentOffset\fP"
.br
.ti -1c
.RI "unsigned short \fBdirty\fP"
.br
.ti -1c
.RI "unsigned short \fBtableType\fP"
.br
.ti -1c
.RI "const unsigned char * \fBdictionary\fP"
.br
.ti -1c
.RI "const \fBLZ4_stream_t_internal\fP * \fBdictCtx\fP"
.br
.ti -1c
.RI "unsigned int \fBdictSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ADBDriverDLL from the source code\&.
