.TH "LZ4_streamDecode_t_internal" 3 "Mon Sep 9 2019" "ADBDriverDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LZ4_streamDecode_t_internal
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const unsigned char * \fBexternalDict\fP"
.br
.ti -1c
.RI "const unsigned char * \fBprefixEnd\fP"
.br
.ti -1c
.RI "size_t \fBextDictSize\fP"
.br
.ti -1c
.RI "size_t \fBprefixSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ADBDriverDLL from the source code\&.
