.TH "stdext::MultiString" 3 "Mon Sep 9 2019" "ADBDriverDLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdext::MultiString
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIs\fP () const"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "template<typename T > void \fBSet\fP (T const &)"
.br
.ti -1c
.RI "template<typename T > T \fBGet\fP ()"
.br
.ti -1c
.RI "const std::wstring & \fBoperator=\fP (const \fBMultiString\fP &) const"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &)"
.br
.ti -1c
.RI "template<typename T > void DLL_EXPORT \fBSet\fP (T const &s)"
.br
.ti -1c
.RI "template<typename T > T DLL_EXPORT \fBGet\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ADBDriverDLL from the source code\&.
