__MENU_ACMD(ID_CMD_POP_MENU30, ResManager::IndexStringPopUpMenu::RES_STR_POPUP_17, 3)
__MENU_ACMD(ID_CMD_POP_MENU31, ResManager::IndexStringPopUpMenu::RES_STR_POPUP_18, 111)
__MENU_ACMD(ID_CMD_POP_MENU32, ResManager::IndexStringPopUpMenu::RES_STR_POPUP_19, 187)
__MENU_ACMD(ID_CMD_POP_MENU33, ResManager::IndexStringPopUpMenu::RES_STR_POPUP_20, 176)
__MENU_ACMD(ID_CMD_POP_MENU34, ResManager::IndexStringPopUpMenu::RES_STR_POPUP_21, 207)
__MENU_ACMD(ID_CMD_POP_MENU35, ResManager::IndexStringPopUpMenu::RES_STR_POPUP_22, 208)
__MENU_ACMD(ID_CMD_POP_MENU36, ResManager::IndexStringPopUpMenu::RES_STR_POPUP_23, 209)
__MENU_ACMD(ID_CMD_POP_MENU37, ResManager::IndexStringPopUpMenu::RES_STR_POPUP_24, 219)
__MENU_ACMD(ID_CMD_POP_MENU38, ResManager::IndexStringPopUpMenu::RES_STR_POPUP_25, 223)
__MENU_ACMD(ID_CMD_POP_MENU39, ResManager::IndexStringPopUpMenu::RES_STR_POPUP_26, 224)

#undef __MENU_ACMD
